### ISSUE TITLE
Thanks-- Trying to set expectations

### ISSUE THREAD

**Issue by crspybits** [wrmack/Get-tokens#1]
Thanks again for your code! I'm trying to set my expectations on what your code currently does, and what might need further work.

I'm getting as far in the execution as:

```
   func presentAuthenticationViewController(request: AuthorizationRequest?, callback: @escaping (AuthorizationResponse?, Error?) -> Void) -> Bool {
```

and in there, `openedSafari` is being set to false.

I think it's because the `redirectScheme`, which I believe is supposed to be a URL scheme defined in the project is currently:

Printing description of redirectScheme:
▿ Optional<String>
  - some : "com.wm.POD-browser"

isn't defined as a specific URL scheme.

Any help is appreciated. Thanks!

**Comment by crspybits** [comment]
I defined `com.wm.POD-browser` as a URL scheme, and same situation.

**Comment by crspybits** [comment]
OK. I'm making some progress. Looks like the initial problem  was that the `ASWebAuthenticationSession` didn't have a `presentationContextProvider`.

**Comment by crspybits** [comment]
Now, I'm getting Safari coming up, but when I try to use:

https://crspybits.inrupt.net (I have created a Pod at inrupt)
or
https://inrupt.net

I get:

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-07-21 at 22 42 42](https://user-images.githubusercontent.com/5758762/126591166-1e5e471e-c6a8-459d-9662-8aa177031f61.png)

**Comment by crspybits** [comment]
OK-- I'm using `https://broker.pod.inrupt.com` now and getting further:

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-07-22 at 01 33 45](https://user-images.githubusercontent.com/5758762/126604095-99b149c9-5094-4146-9680-f13f575574bf.png)

**Comment by wrmack** [comment]
I'm impressed you got that far!  The last time I updated the code it worked fine (except for the noted issue with solid-server which has now been fixed).  However, since then there will have been changes in Swift and Solid-server so the code probably needs a complete overhaul.  I believe Inrupt now uses a different solid server - Enterprise Solid Server - to that used by https://solidcommunity.net - which is more like the version I used for testing, so you might like to try it against that.  I have a bit of time this weekend (I no longer work Fridays) so will also have a look.

**Comment by wrmack** [comment]
I would also note that I used the code from Get-tokens in [Profile-browser](https://github.com/wrmack/Profile-browser) which might be of interest to you.

**Comment by wrmack** [comment]
So... I opened in Xcode and changed settings to iOS 14.5.  Ran in simulator and entered my account at solidcommunity.net.  It ran but ultimately crashed. So will try to fix.

![Get-tokens](https://user-images.githubusercontent.com/1266035/126615048-690db1b6-3522-40ad-89a0-84ccdf5c3218.gif)

**Comment by crspybits** [comment]
Cool! Thanks for the response. I look forward to the updates. It looks like yours is perhaps the only iOS native code for doing Solid sign-in. I did get a little further but ended up with the following. I'm completely new to Solid so very little clue yet :). I am hoping to move towards a Swift Package Manager library that I can use in my existing app to allow Solid sign in. It has its own general sign in system (allowing access to other, more traditional cloud storage systems) so I'm hoping to limit the UI of that library to just the `ASWebAuthenticationSession`. Not sure what your goals are, but I'd be very happy to work with you on that.

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-07-22 at 01 35 40](https://user-images.githubusercontent.com/5758762/126650151-245c373f-1a74-438e-96bc-113fbe430ff5.png)

**Comment by wrmack** [comment]
My own interests are mainly in online voting.  There is something that feels right about a voter not submitting a vote to an election server (and thereby parting with it) but rather saving it to a pod and telling the election authority to come and count it.  I am interested in the work Professor Verborgh is [doing with the Flemish government](https://ruben.verborgh.org/publications/buyle_egose_2019/).  The [area of study around online voting](https://wrmack.github.io/Online-voting/) is fraught with security issues.  Most online voting solutions are browser-based and make heavy use of cryptography.  My intuition is that the Apple ecosystem is more secure with its sandboxing etc.  There are two open source online voting applications that are of interest in academia - [Helios](https://vote.heliosvoting.org) and [Belenios](https://www.belenios.org).  Helios is written in python using the Django framework.  I have made a small [contribution to its documentation](https://wrmack.github.io/helios-server-docs/site/).  Belenios is written in OCaml, which was totally new to me but Belenios is very promising because it is being actively developed by [French computer scientists](https://www.belenios.org/aboutus.html).    All this is to explain that I have become a bit distracted from developing in Swift.  I have a Swift app SpeakerTracker which I have recently returned to, to refactor in SwiftUI.

**Comment by wrmack** [comment]
I now have it working for [solidcommunity.net and inrupt.net servers but not Inrupt.com (Pod spaces)](https://solidproject.org/users/get-a-pod).  The only issue was `presentationContextProvider` was came in iOS 13.

![get-tokens](https://user-images.githubusercontent.com/1266035/126721139-e74a89c4-8cf1-40c5-b99a-90dc359dd595.gif)

**Comment by wrmack** [comment]
Now looking at why it is not working with inrupt.com.  Looks like the flow spec has changed since I developed Get-tokens.  It now includes [DPoP tokens](https://solid.github.io/authentication-panel/solid-oidc/).

https://solidcommunity.net/.well-known/openid-configuration contains `"token_types_supported":["legacyPop","dpop"]`

https://broker.pod.inrupt.com/.well-known/openid-configuration does not indicate it supports legacy POP.

I need to get my head around how the whole flow works again.  Reading [IETF draft](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop-03).

**Comment by crspybits** [comment]
Thanks! I pulled your updates, made a Pod on `solidcommunity.net` and it works for me too.

The voting idea sounds cool. I'll start breaking some ground on a Swift Package Manager adaptation of your code shortly. Hope that's OK if I base my work off yours. I'll certainly reference yours.

**Comment by wrmack** [comment]
No problem.  My motivation is simply to contribute what I can.

**Comment by crspybits** [comment]
Cool. I'd appreciate any help I can get :). 

I'm looking at https://solid.github.io/authentication-panel/solid-oidc-primer/#request-flow and learning about DPoP. I wondering if that's what's supported by https://broker.pod.inrupt.com. It's a rather different auth flow than I've seen before. My situation is a little more complicated too in that I have a separate server (not a Pod server) that will also be talking directly to the Pod. The description in https://solid.github.io/authentication-panel/solid-oidc-primer/#request-flow doesn't seem to account for that variation. 

Though I see now that that is a draft document I linked above. Seems this is more "solid"? :) https://solid.github.io/authentication-panel/solid-oidc/

**Comment by wrmack** [comment]
This is Inrupt’s Enterprise Server documentation regarding authentication:  https://docs.inrupt.com/ess/latest/security/authentication/ <https://docs.inrupt.com/ess/latest/security/authentication/>

It seems standard OIDC stuff and references this: https://solid.github.io/authentication-panel/solid-oidc/ <https://solid.github.io/authentication-panel/solid-oidc/> 


I think what you intend to do should work.

**Comment by crspybits** [comment]
Making some headway:
https://github.com/crspybits/SolidAuthSwift

So far my token request (using DPoP) isn't working yet: https://github.com/solid/solidcommunity.net/issues/48

**Comment by crspybits** [comment]
Got it now! I wasn't forming part of the JWT correctly.

**Comment by wrmack** [comment]
Congratulations.  You are certainly ahead of me.  I have been reminding myself of all the specs I read up when I put Get tokens together.

**Comment by wrmack** [comment]
For reference - when I developed Get-tokens I used as reference code:

https://github.com/openid/AppAuth-iOS <https://github.com/openid/AppAuth-iOS>  
https://openid.github.io/AppAuth-iOS/ <https://openid.github.io/AppAuth-iOS/>
https://github.com/OAuthSwift <https://github.com/OAuthSwift>
https://github.com/airsidemobile/JOSESwift <https://github.com/airsidemobile/JOSESwift>  (JSON web token code)

The first two links are provided by the OpenID organisation and I guess could be considered reliable code.  The repository is actively maintained, though there are currently 124 open issues.  The code does not include the DPOP protocol.

**Comment by wrmack** [comment]
I have refactored Get tokens with SwiftUI and created a separate repository for it.  [https://github.com/wrmack/GetTokens-SwiftUI](https://github.com/wrmack/GetTokens-SwiftUI).  Still needs considerable refactoring.  I am using dynamic registration to register client and not getting DPoP access tokens from solidcommunity.net or inrupt.net, but inrupt.com is returning a dpop access token - seems to work OK.  It also uses client_name when authorizing instead of 'null'. 

Archiving this repository.
